name: Générer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Compilation Forcée
        run: |
          # On compile
          find . -name "build.gradle.kts" -not -path "*/.*" -execdir gradle assembleDebug \;
          
          # ETAPE CRUCIALE : On crée un dossier 'sortie' et on y déplace l'APK trouvé
          mkdir -p sortie_apk
          find . -name "*.apk" -exec cp {} sortie_apk/ \;

      - name: Téléverser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          # On pointe directement sur notre nouveau dossier
          path: sortie_apk/*.apk
