name: Generer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Verifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Reparer et Compiler
        run: |
          # 1. On installe Gradle sur la machine GitHub
          sudo apt-get update && sudo apt-get install -y gradle
          
          # 2. On entre dans le dossier où se trouve votre projet
          # D'après vos photos, c'est : Assistante Ollama/AssistantOllama
          cd "Assistante Ollama/AssistantOllama"
          
          # 3. On génère le fichier gradlew manquant
          gradle wrapper
          chmod +x gradlew
          
          # 4. On lance la compilation de l'APK
          ./gradlew assembleDebug

      - name: Televerser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          path: "**/*.apk"
          if-no-files-found: error
