name: Generer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Verifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilation avec Gradle
        # On dit à GitHub d'exécuter les commandes DANS le dossier de votre application
        working-directory: "Assistante Ollama" 
        run: |
          # On utilise le wrapper gradle du projet (plus fiable)
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Televerser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          # On cherche l'APK partout dans le dépôt
          path: "**/*.apk"
          if-no-files-found: error
