name: Generateur APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Generer le Gradle Wrapper
        # Cette etape installe Gradle sur le serveur GitHub juste pour creer le wrapper
        working-directory: "./Assistante Ollama"
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle wrapper --gradle-version 8.5

      - name: Accorder les permissions d'execution
        working-directory: "./Assistante Ollama"
        run: chmod +x gradlew

      - name: Compiler l'APK Debug
        working-directory: "./Assistante Ollama"
        run: ./gradlew assembleDebug --stacktrace

      - name: Televerser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          path: "Assistante Ollama/app/build/outputs/apk/debug/*.apk"
