name: Generer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Verifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Compilation et Extraction
        run: |
          # 1. On cherche le fichier build.gradle et on lance la compilation
          # On utilise find pour supporter les sous-dossiers si nécessaire
          find . -name "build.gradle*" -not -path "*/.*" -execdir gradle assembleDebug \;
          
          # 2. Création du dossier final
          mkdir -p mon_apk_final
          
          # 3. Copie de TOUS les APK trouvés vers le dossier final
          find . -name "*.apk" -exec cp {} mon_apk_final/ \;
          
          # 4. Vérification visuelle dans les logs
          ls -lh mon_apk_final/

      - name: Televerser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          # On utilise un chemin large pour être sûr de ne rien rater
          path: "mon_apk_final/*.apk"
          if-no-files-found: error
