name: Generer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Verifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Reparateur et Compilateur
        run: |
          # 1. On installe Gradle sur la machine
          sudo apt-get update && sudo apt-get install -y gradle
          
          # 2. MAGIE : On cherche le dossier qui contient 'settings.gradle.kts'
          # Cela évite les erreurs de nom de dossier
          PROJET_PATH=$(find . -name "settings.gradle.kts" -exec dirname {} \;)
          echo "Dossier trouvé : $PROJET_PATH"
          cd "$PROJET_PATH"
          
          # 3. On crée le fichier de commande manquant
          gradle wrapper
          chmod +x gradlew
          
          # 4. On lance la compilation
          ./gradlew assembleDebug

      - name: Televerser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          path: "**/*.apk"
          if-no-files-found: error
