name: Générer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' # Accélère les prochaines compilations

      - name: Accorder les permissions d'exécution à gradlew
        run: chmod +x gradlew
        working-directory: "Assistante Ollama"

      - name: Générer un APK Debug
        run: ./gradlew assembleDebug
        working-directory: "Assistante Ollama"

      - name: Téléverser le fichier APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "Assistante Ollama/app/build/outputs/apk/debug/*.apk"
