name: Generateur APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurer Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

      - name: Compiler l'APK
        run: |
          # On entre directement dans le dossier du projet
          cd "Assistante Ollama"
          # On lance la compilation
          gradle assembleDebug --stacktrace

      - name: Televerser l'APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          path: "**/build/outputs/apk/debug/*.apk"
