name: Générer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Compilation Totale
        run: |
          # On cherche le dossier qui contient VRAIMENT le fichier settings
          CHEMIN_PROJET=$(find . -name "settings.gradle.kts" -exec dirname {} \; | head -n 1)
          echo "Le coeur du projet est ici : $CHEMIN_PROJET"
          cd "$CHEMIN_PROJET"
          
          # On cherche le dossier qui contient le code (application)
          DOSSIER_APP=$(find . -name "build.gradle.kts" ! -path "./build.gradle.kts" -exec dirname {} \; | head -n 1)
          echo "Le dossier de l'app est : $DOSSIER_APP"
          
          # On lance la compilation du module spécifique
          gradle :application:assembleDebug --stacktrace

      - name: Téléverser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: APK_Assistant_Ollama
          path: "**/*.apk"
