name: Générer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Compilation Finale
        run: |
          # 1. On trouve le dossier qui contient le fichier settings
          CHEMIN_RACINE=$(find . -name "settings.gradle.kts" -exec dirname {} \; | head -n 1)
          cd "$CHEMIN_RACINE"
          
          # 2. On lance la compilation de TOUS les modules trouvés
          # Cela évite l'erreur "Project application not found"
          gradle assembleDebug --stacktrace

      - name: Téléverser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          path: "**/*.apk"
