name: Générer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Compiler l'APK
        run: |
          # On entre dans le double dossier
          cd "Assistante Ollama/Assistante Ollama"
          gradle assembleDebug

      - name: Téléverser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: mon-application-ollama
          # Le chemin vers l'APK final après la compilation
          path: "**/build/outputs/apk/debug/*.apk"
