name: Generer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Verifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Reparateur et Compilateur
        run: |
          # 1. On installe Gradle
          sudo apt-get update && sudo apt-get install -y gradle
          
          # 2. On trouve le dossier du projet
          PROJET_PATH=$(find . -name "settings.gradle.kts" -exec dirname {} \;)
          cd "$PROJET_PATH"
          
          # 3. On génère le wrapper avec une version RECENTE (8.5)
          # C'est l'étape qui corrige l'erreur sur Java 17
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
          
          # 4. On lance la compilation
          ./gradlew assembleDebug

      - name: Televerser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          path: "**/*.apk"
          if-no-files-found: error
