name: Generer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Verifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilation automatique
        run: |
          # Cette commande trouve le fichier gradlew peu importe où il est caché
          GRADLEW_PATH=$(find . -name gradlew | head -n 1)
          
          if [ -z "$GRADLEW_PATH" ]; then
            echo "ERREUR : Fichier gradlew introuvable dans le dépôt !"
            exit 1
          fi
          
          # On se déplace dans le dossier contenant gradlew
          cd $(dirname "$GRADLEW_PATH")
          
          # On lance la compilation
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Televerser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          path: "**/*.apk"
          if-no-files-found: error
