name: Generateur APK

on:
  workflow_dispatch: # Permet de lancer la compilation manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurer Gradle
        # Cette action installe Gradle automatiquement
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

      - name: Compiler l'APK
        run: |
          # 1. On cherche dynamiquement le dossier qui contient le fichier settings
          PROJET_PATH=$(find . -name "settings.gradle.kts" -exec dirname {} \; | head -n 1)
          echo "Projet trouve dans le dossier : $PROJET_PATH"
          
          # 2. On entre dans ce dossier
          cd "$PROJET_PATH"
          
          # 3. On lance la compilation avec Gradle
          gradle assembleDebug --stacktrace

      - name: Televerser l'APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          # Cherche tous les fichiers .apk generes recursivement
          path: "**/build/outputs/apk/debug/*.apk"
