name: Générer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Compilation et Capture
        run: |
          # 1. On compile partout où on trouve un projet
          find . -name "build.gradle.kts" -not -path "*/.*" -execdir gradle assembleDebug \;
          
          # 2. On crée un dossier de sortie à la RACINE absolue du projet
          mkdir -p $GITHUB_WORKSPACE/output_apk
          
          # 3. On cherche tous les .apk et on les COPIE de force dans ce dossier
          find . -name "*.apk" -exec cp {} $GITHUB_WORKSPACE/output_apk/ \;
          
          # 4. Debug : On vérifie si le dossier contient bien quelque chose
          ls -R $GITHUB_WORKSPACE/output_apk/

      - name: Téléverser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_APK
          path: output_apk/
          if-no-files-found: error
