name: Generer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Verifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Reparateur et Compilateur
        run: |
          # 1. Installation de Gradle
          sudo apt-get update && sudo apt-get install -y gradle
          
          # 2. Trouver le dossier du projet
          PROJET_PATH=$(find . -name "settings.gradle.kts" -exec dirname {} \;)
          cd "$PROJET_PATH"
          
          # 3. Force la mise à jour du wrapper et des permissions
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
          
          # 4. Nettoyage et Compilation avec option pour ignorer les erreurs de plugins locales
          # On ajoute --stacktrace pour voir exactement quel dépôt bloque si ça échoue
          ./gradlew assembleDebug --stacktrace

      - name: Televerser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          path: "**/*.apk"
          if-no-files-found: error
