name: Generer APK

on:
  workflow_dispatch:

jobs:
  construire:
    runs-on: ubuntu-latest

    steps:
      - name: Verifier le code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installation de Gradle et Compilation
        run: |
          sudo apt-get update && sudo apt-get install -y gradle
          # On cherche tous les fichiers build.gradle et on lance la compilation dans leur dossier
          find . -name "build.gradle*" -execdir gradle assembleDebug \;

      - name: Televerser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon_Assistant_Ollama
          # Cette ligne est la plus importante : elle cherche n'importe quel APK 
          # généré dans tout le projet, peu importe le dossier.
          path: "**/*.apk"
          if-no-files-found: error
